### ISSUE TITLE
Support Separate Consumer Group

### ISSUE THREAD

**Issue by josagonzalez** [Microsoft/AzureFunctionforSplunkVS#12]
I'm trying to consume diagnostic logs from an event hub that is being consumed somewhere else. I know a good way to consume into multiple destinations is with consumer groups. [This stackoverflow](https://stackoverflow.com/questions/42948741/configure-custom-consumergroup-using-eventhubtrigger) mentions there's a `ConsumerGroup` property in EventHubTrigger, but that's not present in the code in this repo. Is there another way to consume from a different consumer group in a given event hub, or would this have to be a feature request?

**Comment by sebastus** [comment]
The TA doesn't know how to use an alternate consumer group. What about the
other consumer of this event hub? Can it be configured to use an alternate
consumer group so the TA can use default?

**Comment by sebastus** [comment]
Another option is to create a second hub and a second diagnostic setting,
directing the same logs to a second event hub.

**Comment by josagonzalez** [comment]
> The TA doesn't know how to use an alternate consumer group

What's the TA in this context?

We may be able to configure the other consumer to use a separate consumer group, but we'd like to move this one away from using the default as well to avoid having multiple consumers in the same consumer group. Also given we're deploying this across our entire infrastructure, we'd like to avoid having to create a second hub for every region and double our current usage.

**Comment by sebastus** [comment]
TA = Technical add-on = splunk's term for the add-on.

The other alternative is to support your own fork of the code.

Change this line to have the correct consumer group name:

https://github.com/Microsoft/AzureMonitorAddonForSplunk/blob/b7bc5cba00ecaebd5b0bc935885bc1aa544ef0c6/bin/app/azure_monitor_logs.js#L630

**Comment by josagonzalez** [comment]
Thanks @sebastus. I'll talk it over with the team and we'll decide which route to take.
