### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by alastairtree** [microsoft/AzureFunctionforSplunkVS#14]
Hi, thanks for the repo.

 I've ported the code to for net core and functions V2. Any interest in me committing it back? Only done limited testing and not using your deployment method (as using terraform instead) so can't guarantee all is perfect but they seem sound enough. Could probably PR the changes over if you want them?

Also do you have any advice on forwarding diagnostic logs from app service and azure functions to splunk? I can't find a native way to ship logs to eventhub so was looking at using serilog and their event hub appender but advice would be welcome.

**Comment by sebastus** [comment]
Hi Alastair,

This sounds fabulous. :)

I'm pretty busy for the next few weeks, so while I'm very interested in
what you've done, I won't have time to look at it for a bit. Please do
submit a PR. Note that I've made a few changes myself in the past week or
two.

re: forwarding diagnostic logs. I don't think I understand the question.
But let me make a guess. You have some logs that you're generating and you
want them to appear in Splunk alongside the usual Activity Log, Diagnostic
Logs (from azure resource providers).

AzureFunctionForSplunkVS will happily ingest anything that conforms to this
structure through the diagnostic log function. Alternatively, build another
function based on the diagnostic log function and use your own event hub.

{
   "records": [
      {...},   <-- json object with your log
      {...},
      {...}
      ...
   ]
}

Event hubs can be an output from a function. So build the above structure
and then route them out through event hub.

https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs#output



Cheers!
Greg

**Comment by alastairtree** [comment]
Ok, I'll try and sort out something like a PR but our use case is probably sufficiently different that I have made enough changes that is more fork and branch at this point, but I will try and commit back what I think is usable.

On the app logging - if I build an API using asp.net core and log out using ILogger then the diagnostic log advice seems to be to write to d:\logfiles? These can then be accessed using FTP or shipped to Azure Storage, or streamed in the portal, but there does not seem to be an out of the box way to ship them to EventHubs like may other azure resources? In which case I have been using Serilog's event hub appender to send them myself, but just checking there is not a better way? Feels like there is more drive to just push them all to app insights but not sure that's useful if you want to splunk them.

**Comment by sebastus** [comment]
I just merged a PR that updates the function runtime to v2, among other things.
