### ISSUE TITLE
Add Function Version to make this work

### ISSUE THREAD

**Issue by v-daodhi** [microsoft/AzureFunctionforSplunkVS#19]
To make this solution work in Azure, kindly change the Function Version on the template. I believe the authors forgot to change the Function Version since this cannot be deployed as V1

Line 232 of the generated ARM template
                        {
                            "name": "FUNCTIONS_EXTENSION_VERSION",
                            "value": "~1"
                        },

changed to 
                        {
                            "name": "FUNCTIONS_EXTENSION_VERSION",
                            "value": "~2"
                        },

**Comment by cocallaw** [comment]
Thanks for the heads up @v-daodhi, we will get this updated.

**Comment by cocallaw** [comment]
The FUNCTIONS_EXTENSION_VERSION has been updated in the ARM template for V2
