### ISSUE TITLE
Debug Mode

### ISSUE THREAD

**Issue by JeremieBethmont** [Microsoft/AzureFunctionforSplunkVS#7]
Hi,
Thanks for sharing these functions!

Is there a way to enable a Debug mode and obtain a more detailed error logs ? Some of my 'custom' functions are failing and I am not able to see the issue in the console.

Example:
`2018-08-22T23:50:10  Welcome, you are now connected to log-streaming service.`
`2018-08-22T23:51:10  No new trace in the past 1 min(s).`
`2018-08-22T23:52:10  No new trace in the past 2 min(s).`
`2018-08-22T23:52:57.870 [Info] Function started (Id=47be3062-4997-49c1-8277-5449b549a927)`
`2018-08-22T23:52:57.917 [Error] Function completed (Failure, Id=47be3062-4997-49c1-8277-5449b549a927, Duration=51ms)`

Thanks,

**Comment by sebastus** [comment]
An Error like that just means that the function threw an exception. You can add log output messages to your code to see more details about the cause.
