### ISSUE TITLE
FaultProcessor failed to send to splunk

### ISSUE THREAD

**Issue by zacharymollenhour** [Microsoft/AzureFunctionforSplunkVS#8]
I keep recieving this error when I try to run the function. I cannot locate the reasoning for it to fail. Any ideas?

**Comment by zacharymollenhour** [comment]
[Error,FaultProcessor] FaultProcessor failed to send to Splunk: 14ef0369-2c21-4195-a7b3-afe2c433ccfe

**Comment by brettroquemore** [comment]
I am getting the same issue.  Seems like it is failing to validate the certificate on splunks cloud.

**Comment by brettroquemore** [comment]
I worked with microsoft and got it working.  Can you look at this code to see what we did. https://github.com/silvermoong/AzureFunctionforSplunkVS.git

**Comment by zacharymollenhour** [comment]
Tried running yours and still recieve the same error. Could you elaborate on what microsoft had you change?

**Comment by zacharymollenhour** [comment]
Got it to work! Thanks for the changes.
