### ISSUE TITLE
Time field needs to be forced to appear at beginning of event

### ISSUE THREAD

**Issue by jijulukose** [microsoft/AzureFunctionforSplunkVS#9]
Splunk's default MAX_TIMESTAMP_LOOKAHEAD is 128 bytes. Unless the event's time field comes within that, Splunk is going to take HEC event received time as event's time which may not be desirable in some cases.
Time field must be forced to appear at the beginning of all event/source types.

**Comment by sebastus** [comment]
@jijulukose Apologies for the delay getting to this. I'll take a look.

**Comment by ScottyMac52** [comment]
Any word on this?

**Comment by sebastus** [comment]
No - never heard back. It's back on my radar screen.

**Comment by sebastus** [comment]
This isn't as easy as you might think. The messages come from many different resources and each has its own format. On top of that, new resources emit into the same event hub as they come online. This means that I can't write a dotnet object for each of them to de-serialize into, placing "time" at the beginning.
Does it matter the name of the time property? I can add an extra time field and put it up front.

**Comment by sebastus** [comment]
I added time to the splunk event metadata. The time of the event is extracted from the message itself and converted to epoch according to HEC metadata definition. This is in the master branch.
